@echo off
del "%HOMEPATH%\Desktop\Discord.ink" /F /Q 
del "%HOMEPATH%\Desktop\Discord.ink - Shortcut" /F /Q 
del "%HOMEPATH%\Desktop\Update.exe" /F /Q 
del "%HOMEPATH%\Desktop\Update.exe - Shortcut" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\Update.exe" /F /Q 
del "%HOMEPATH%\Desktop\Discord.exe" /F /Q 
del "%HOMEPATH%\Desktop\Discord.exe - Shortcut" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\Squirrel.exe" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\Squirrel.exe" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\Squirrel.exe" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\Squirrel.exe" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\SquirrelSetup.log" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\SquirrelSetup.log" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\SquirrelSetup.log" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\SquirrelSetup.log" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\SquirrelSetup.log" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\SquirrelSetup.log" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\Squirrel.exe" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\SquirrelSetup.log" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\Squirrel.exe" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\SquirrelSetup.log" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\Squirrel.exe" /F /Q 
del "%HOMEPATH%\appdata\Local\Discord\SquirrelSetup.log" /F /Q 
del "%HOMEPATH%\appdata\Local\Discord\Discord_updater_r00000.log" /F /Q 
del "%HOMEPATH%\appdata\Local\Discord\Discord_updater_r00001.log" /F /Q 
del "%HOMEPATH%\appdata\Local\Discord\Discord_updater_rCURRENT.log" /F /Q 
rmdir /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_cloudsync" 
rmdir /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_cloudsync" 
rmdir /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_cloudsync" 
rmdir /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_cloudsync" 
rmdir /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_dispatch" 
rmdir /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_dispatch" 
rmdir /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_dispatch" 
rmdir /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_dispatch" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_erlpack" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_erlpack" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_erlpack" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_erlpack" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_game_utils" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_game_utils" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_game_utils" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_game_utils" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_media" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_media" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_media" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_media" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_spellcheck" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_spellcheck" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_spellcheck" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_spellcheck" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_krisp" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_krisp" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_krisp" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_krisp" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_cloudsync" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_dispatch" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_erlpack" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_game_utils" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_media" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_spellcheck" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_krisp" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_cloudsync-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_dispatch-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_erlpack-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_game_utils-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_media-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_spellcheck-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_krisp-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_cloudsync-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_dispatch-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_erlpack-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_game_utils-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_media-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_spellcheck-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_spellcheck-2" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_krisp-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_hook-1" 
rmdir /s /q "%HOMEPATH%\AppData\Local\Discord\app-1.0.9006\swiftshader" 
del "%HOMEPATH%\AppData\Roaming\discord\Cache" /F /Q 
del "%HOMEPATH%\AppData\Local\Discord\app-1.0.9006\swiftshader" /F /Q 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_rpc" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_rpc" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_rpc" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_rpc" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_overlay2" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_overlay2" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_overlay2" 
rd /s /q "%HOMEPATH%\appdata\Roaming\discord\1.0.9006\modules\discord_overlay2" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_rpc" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_overlay2" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_rpc-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_overlay2-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_rpc-1" 
rmdir /s /q "%HOMEPATH%\appdata\Local\Discord\app-1.0.9006\modules\discord_overlay2-1" 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\am.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ar.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\bg.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\bn.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ca.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\cs.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\da.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\de.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\el.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\en-GB.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\es.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\es-419.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\et.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\fa.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\fi.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\fil.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\fr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\gu.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\he.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\hi.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\hr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\hu.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\id.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\it.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ja.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\kn.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ko.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\lt.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\lv.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ml.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\mr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ms.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\nb.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\nl.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\pl.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\pt-br.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\pt-pt.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ro.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ru.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sk.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sl.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sv.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sw.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ta.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\te.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\th.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\tr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\uk.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\vi.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\zh-cn.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\zh-tw.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\am.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ar.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\bg.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\bn.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ca.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\cs.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\da.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\de.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\el.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\en-GB.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\es.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\es-419.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\et.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\fa.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\fi.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\fil.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\fr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\gu.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\he.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\hi.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\hr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\hu.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\id.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\it.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ja.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\kn.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ko.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\lt.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\lv.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ml.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\mr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ms.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\nb.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\nl.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\pl.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\pt-pt.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ro.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ru.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sk.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sl.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sv.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\sw.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\ta.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\te.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\th.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\tr.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\uk.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\vi.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\zh-cn.pak" /F /Q 
del "%HOMEPATH%\appdata\Local\discord\app-1.0.9006\locales\zh-tw.pak" /F /Q 